#!/bin/bash

SSL_DIR="./certs"

if [ "$1" = "" ] ; then
  echo " usage: `basename $0` -f <domain>  .... -f force"
  exit 0
fi

if [ "$1" = "-f" ] ; then
  rm -f $SSL_DIR/*
  shift
fi

DOMAIN="$1"


if [ -e $SSL_DIR/$DOMAIN.key -a -e $SSL_DIR/$DOMAIN.crt ] ; then
  exit 0
fi

# A blank passphrase
PASSPHRASE=""

# Set our CSR variables
SUBJ="/C=HU/ST=XX/L=Budapest/O=ZSIN/OU=XX/CN=machine/emailAddress=zsliga@freemail.dc.hu"

# Create our SSL directory
# in case it doesn't exist
sudo mkdir -p "$SSL_DIR"

# Generate our Private Key, CSR and Certificate
sudo openssl genrsa -out "$SSL_DIR/$DOMAIN.key" 2048
sudo openssl req -new -subj $SUBJ -key "$SSL_DIR/$DOMAIN.key" -out "$SSL_DIR/$DOMAIN.csr" -passin pass:$PASSPHRASE
sudo openssl x509 -req -days 365 -in "$SSL_DIR/$DOMAIN.csr" -signkey "$SSL_DIR/$DOMAIN.key" -out "$SSL_DIR/$DOMAIN.crt"
